# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsresource',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Profile'),
        ),
        migrations.AddField(
            model_name='awsresource',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Region'),
        ),
    ]
