# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_auto_20160921_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2LaunchOptionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('az', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Profile')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Region')),
            ],
        ),
    ]
