# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0005_ec2launchoptionset_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Profile')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Region')),
            ],
        ),
    ]
