# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0006_elb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELBGenericUpdateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elb_name', models.CharField(max_length=1000)),
                ('instances_reg', models.TextField()),
                ('instances_dereg', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('stage', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Profile')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='launcher.Region')),
            ],
        ),
    ]
